---
title: "MEL_DMSO"
author: "YDL"
date: "2021/9/26"
output:
  pdf_document:
    latex_engine: xelatex
  word_document: default
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = F,message = F,collapse=TRUE)
```

#读入数据
```{r}
library("biomaRt")
library("org.Hs.eg.db")
library("org.Mm.eg.db")
library("DESeq2")
library(edgeR)
library(limma)
library("Rgraphviz")
rm(list=ls())
getwd()
setwd("C:/Users/yudonglin/Desktop/单细胞数据/各种造血相关的数据/MEL")


count<-read.table("GSE133343_MEL_all_samples.txt",header = T)
dim(count)
head(count)
count<-count[!duplicated(count$gene_short_name),]#去除人类基因重复值
rownames(count)<-count$gene_short_name
count_all<-count[,c(7:10)]
head(count_all)
cts<-count_all
write.csv(cts,"expression_mel.csv")
```

#PCA
```{r}
#PCA
condition<-factor(c("uninduced","uninduced","induced","induced"), levels = c("uninduced","induced"))
head(cts)
tmp<-cts[,c(1:4)]
head(tmp)
cts<-round(cts)
colData <- data.frame(row.names=colnames(cts[,c(1:4)]), condition)
head(colData,10)
dds_all<- DESeqDataSetFromMatrix(countData = cts[,c(1:4)],colData = colData,design= ~condition)
head(dds_all)
dds_all<- DESeq(dds_all)
vsd_all<-vst(dds_all,blind=FALSE)
head(vsd_all)
#dist(t(assay(vsd_all)))
plotPCA(vsd_all,intgroup="condition")
```

#样本聚类
```{r}
#样本的聚类图
sampleDists <- dist(t(assay(vsd_all)))
library("RColorBrewer")
library(pheatmap)
sampleDistMatrix <- as.matrix(sampleDists)
rownames(sampleDistMatrix) <- paste(vsd_all$condition, vsd_all$type, sep="")
colnames(sampleDistMatrix) <- NULL
colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
pheatmap(sampleDistMatrix,
         clustering_distance_rows=sampleDists,
         clustering_distance_cols=sampleDists,
         col=colors)
```

#样本相关性
```{r}
cor(cts,method = "pearson")
heatmap(cor(cts))
```

#根据基因表达数据对样本进行分类
```{r}
#根据基因表达数据对样本进行分类
cor(cts)->r 
heatmap(r)
as.dist(1-r)->d  #用相关性，构建样本距离矩阵

hc1<-hclust(d, "single") #最短距离法
hc2<-hclust(d, "complete") #最长距离法
hc3<-hclust(d, "median") #中间距离法
hc4<-hclust(d, "mcquitty") #Mcquitty相似法
par(mfrow = c(2, 2))

plot(hc1,hang=-1) 
plot(hc2,hang=-1) #hang参数，确定类的摆放位置
plot(hc3,hang=-1)
plot(hc4,hang=-1)
```

#差异表达分析
```{r}
#做一下差异表达分析
res_all <- results(dds_all)
head(res_all)
res_all <- res_all[order(res_all$padj),]
head(res_all)
diff_gene <- subset(res_all, padj < 0.05 & (log2FoldChange < -1|log2FoldChange > 1))
head(diff_gene)
dim(diff_gene)
head(res_all)
write.csv(diff_gene,file = "diff_gene_all.csv",row.names = T)
diff_gene_up <- subset(res_all, padj < 0.05 & (log2FoldChange > 1))
write.csv(diff_gene_up,file = "diff_gene_up.csv",row.names = T)
diff_gene_down <- subset(res_all, padj < 0.05 & (log2FoldChange < -1))
write.csv(diff_gene_down,file = "diff_gene_down.csv",row.names = T)
dim(diff_gene)
dim(diff_gene_up)
dim(diff_gene_down)

diff_gene<-na.omit(diff_gene)
write.csv(diff_gene,file = "dataset.csv",row.names = T)
```

#火山图
```{r}
#火山图
library(ggplot2)
dataset <-read.csv('dataset.csv',header = TRUE)

cut_off_pvalue = 0.0000001
cut_off_log2FoldChange = 1
dataset$change = ifelse(dataset$pvalue < cut_off_pvalue & abs(dataset$log2FoldChange) >= cut_off_log2FoldChange,ifelse(dataset$log2FoldChange>cut_off_log2FoldChange ,'Up','Down'), 'Stable')
p<- ggplot(dataset,aes(x = log2FoldChange, y = -log10(pvalue),colour=change))+labs(title= "vocano plot") +geom_point(alpha=0.4, size=3.5) +scale_color_manual(values=c("#546de5","#d2dae2","#ff4757"))+geom_vline(xintercept=c(-1,1),lty=4,col="black",lwd=0.8) +geom_hline(yintercept =-log10(cut_off_pvalue),lty=4,col="black",lwd=0.8) +labs(x="log2(fold change)", y="-log10 (p-value)")+ theme_bw()+theme(plot.title = element_text(hjust = 0.5), legend.position="right",        legend.title = element_blank() )

library(ggrepel)
dataset$change = ifelse(dataset$pvalue < cut_off_pvalue & abs(dataset$log2FoldChange) >= cut_off_log2FoldChange,ifelse(dataset$log2FoldChange> cut_off_log2FoldChange ,'Up','Down'), 'Stable')

dataset$label = ifelse(dataset$pvalue <cut_off_pvalue & abs(dataset$log2FoldChange) >= 1,as.character(dataset$X),"")

p+geom_text_repel(data = dataset, aes(x =dataset$log2FoldChange, y =-log10(dataset$pvalue), label =label), size = 3,box.padding =unit(0.5, "lines"),point.padding = unit(0.8,"lines"),segment.color ="black",show.legend = FALSE)


```

#富集分析
```{r}
library(clusterProfiler)
library("org.Mm.eg.db")
library(ggplot2)


#上调基因的富集分析
a <- read.csv("diff_gene_up.csv")
b<-a$X
eg = bitr(b, fromType="SYMBOL", toType="ENTREZID", OrgDb ="org.Mm.eg.db")
gene <- eg[,2]
head(gene)
#分子功能(MolecularFunction)

ego <- enrichGO(
  
  gene          = gene,
  
  keyType = "ENTREZID",
  
  OrgDb         = org.Mm.eg.db,
  
  ont           = "MF",
  
  pAdjustMethod = "BH",
  
  pvalueCutoff  = 0.05,
  
  qvalueCutoff  = 0.05,
  
  readable      = TRUE)

barplot(ego)



dotplot(ego)



pdf("GO_MF_up.pdf",width=10,height=6)

barplot(ego)
dotplot(ego)

dev.off()

write.csv(ego,file="GO_MF_up.csv")



#生物过程(biologicalprocess)

ego <- enrichGO(
  
  gene          = gene,
  
  keyType = "ENTREZID",
  
  OrgDb         = org.Mm.eg.db,
  
  ont           = "BP",
  
  pAdjustMethod = "BH",
  
  pvalueCutoff  = 0.05,
  
  qvalueCutoff  = 0.05,
  
  readable      = TRUE)

barplot(ego)



dotplot(ego)



pdf("GO_BP_up.pdf",width=10,height=6)

barplot(ego)
dotplot(ego)

dev.off()

write.csv(ego,file="GO_BP_up.csv")



#细胞组成(cellularcomponent)

ego <- enrichGO(
  
  gene          = gene,
  
  keyType = "ENTREZID",
  
  OrgDb         = org.Mm.eg.db,
  
  ont           = "CC",
  
  pAdjustMethod = "BH",
  
  pvalueCutoff  = 0.05,
  
  qvalueCutoff  = 0.05,
  
  readable      = TRUE)

barplot(ego)



dotplot(ego)



pdf("GO_CC_up.pdf",width=10,height=6)

barplot(ego)
dotplot(ego)
dev.off()

write.csv(ego,file="GO_CC_up.csv")



ekegg <- enrichKEGG(
  
  gene          = gene,
  
  keyType     = "kegg",
  
  organism   = "mmu",
  
  pvalueCutoff      = 0.05,
  
  pAdjustMethod     = "BH",
  
  qvalueCutoff  = 0.05
  
)

barplot(ekegg)



dotplot(ekegg)

write.csv(ekegg,file="kegg_up.csv")

pdf("KEGG_up.pdf",width=10,height=6)

barplot(ekegg)

dotplot(ekegg)


dev.off()

ego <- enrichGO(gene = gene,
                OrgDb = org.Mm.eg.db, 
                pvalueCutoff =0.05, 
                qvalueCutoff = 0.05,
                ont="all",
                readable =T)
pdf("GO_up.pdf",width=10,height=6)
barplot(ego)
dotplot(ego)
#柱状图,各自展示前8个term
barplot(ego,drop = TRUE, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
#气泡图,各自展示前8个term
dotplot(ego, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
dev.off()

barplot(ego)
dotplot(ego)
#柱状图,各自展示前8个term
barplot(ego,drop = TRUE, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
#气泡图,各自展示前8个term
dotplot(ego, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')




library(clusterProfiler)
library("org.Mm.eg.db")
library(ggplot2)


#cluster0的marker
a <- read.csv("diff_gene_down.csv")
b<-a$X
eg = bitr(b, fromType="SYMBOL", toType="ENTREZID", OrgDb ="org.Mm.eg.db")
gene <- eg[,2]
head(gene)
#分子功能(MolecularFunction)

ego <- enrichGO(
  
  gene          = gene,
  
  keyType = "ENTREZID",
  
  OrgDb         = org.Mm.eg.db,
  
  ont           = "MF",
  
  pAdjustMethod = "BH",
  
  pvalueCutoff  = 0.05,
  
  qvalueCutoff  = 0.05,
  
  readable      = TRUE)

barplot(ego)



dotplot(ego)



pdf("GO_MF_down.pdf",width=10,height=6)

barplot(ego)
dotplot(ego)

dev.off()

write.csv(ego,file="GO_MF_down.csv")



#生物过程(biologicalprocess)

ego <- enrichGO(
  
  gene          = gene,
  
  keyType = "ENTREZID",
  
  OrgDb         = org.Mm.eg.db,
  
  ont           = "BP",
  
  pAdjustMethod = "BH",
  
  pvalueCutoff  = 0.05,
  
  qvalueCutoff  = 0.05,
  
  readable      = TRUE)

barplot(ego)



dotplot(ego)



pdf("GO_BP_down.pdf",width=10,height=6)

barplot(ego)
dotplot(ego)

dev.off()

write.csv(ego,file="GO_BP_down.csv")



#细胞组成(cellularcomponent)

ego <- enrichGO(
  
  gene          = gene,
  
  keyType = "ENTREZID",
  
  OrgDb         = org.Mm.eg.db,
  
  ont           = "CC",
  
  pAdjustMethod = "BH",
  
  pvalueCutoff  = 0.05,
  
  qvalueCutoff  = 0.05,
  
  readable      = TRUE)

barplot(ego)



dotplot(ego)



pdf("GO_CC_down.pdf",width=10,height=6)

barplot(ego)
dotplot(ego)
dev.off()

write.csv(ego,file="GO_CC_down.csv")



ekegg <- enrichKEGG(
  
  gene          = gene,
  
  keyType     = "kegg",
  
  organism   = "mmu",
  
  pvalueCutoff      = 0.05,
  
  pAdjustMethod     = "BH",
  
  qvalueCutoff  = 0.05
  
)

barplot(ekegg)



dotplot(ekegg)

write.csv(ekegg,file="kegg_down.csv")

pdf("KEGG_down.pdf",width=10,height=6)

barplot(ekegg)

dotplot(ekegg)


dev.off()

ego <- enrichGO(gene = gene,
                OrgDb = org.Mm.eg.db, 
                pvalueCutoff =0.05, 
                qvalueCutoff = 0.05,
                ont="all",
                readable =T)
pdf("GO_down.pdf",width=10,height=6)
barplot(ego)
dotplot(ego)
#柱状图,各自展示前8个term
barplot(ego,drop = TRUE, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
#气泡图,各自展示前8个term
dotplot(ego, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
dev.off()
barplot(ego)
dotplot(ego)
#柱状图,各自展示前8个term
barplot(ego,drop = TRUE, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
#气泡图,各自展示前8个term
dotplot(ego, showCategory =8,split="ONTOLOGY") + facet_grid(ONTOLOGY~., scale='free')
```

#展示表达模式的热图
```{r}
library(pheatmap)
diff_gene <- subset(res_all, padj < 0.05 & (log2FoldChange < -3|log2FoldChange > 3))
head(diff_gene)
dim(diff_gene)
diff_gene<-as.data.frame(diff_gene)
term<-rownames(diff_gene)
newdata<-cts[c(term),]
pheatmap(newdata,scale ="row",border_color = NA)
pheatmap(newdata,scale ="row",border_color = NA,color = colorRampPalette(colors = c("blue","white","red"))(100))
pheatmap(newdata,scale ="row",cluster_rows = T,border_color = NA,color = colorRampPalette(colors = c("blue","white","red"))(100))
pheatmap(newdata,cluster_rows =T,scale = "row",clustering_method = "average",fontsize=5,fontsize_row=5,fontsize_col=10,color=colorRampPalette(rev(c("red","white","blue")))(102))

```




